<?php
return [
    'adminEmail'          => 'admin@example.com',
    'bsVersion'           => '4.x', //For style select2
    'bsDependencyEnabled' => false,
    'baseUrlBack'  => "http://".$_SERVER['HTTP_HOST'].":81/",
    'baseUrlFront' => "http://localhost",
    'diassemana'   => ["Domingo","Lunes","Martes","Miercoles","Jueves","Viernes","Sábado"],
    'meses'        => ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],
    'social-networks' => [
        "facebook"  => "https://www.facebook.com/",
        "whatsapp"  => "https://wa.me/+5212212224916"
    ],
    'ticketstorage' => "+10 minute",
    'states' => [
            'all'      => 'Todos',
            'Aguascalientes'      => 'Aguascalientes',
            'Baja California'     => 'Baja California',
            'Baja California Sur' => 'Baja California Sur',
            'Campeche'            => 'Campeche',
            'Coahuila'            => 'Coahuila',
            'Colima'              => 'Colima',
            'Chiapas'             => 'Chiapas',
            'Chihuahua'           => 'Chihuahua',
            'cdmx'                => 'CDMX',
            'Durango'             => 'Durango',
            'Guanajuato'          => 'Guanajuato',
            'Guerrero'            => 'Guerrero',
            'Hidalgo'             => 'Hidalgo',
            'Jalisco'             => 'Jalisco',
            'Estado de México'    => 'Estado de México',
            'Michoacán'           => 'Michoacán',
            'Morelos'             => 'Morelos',
            'Nayarit'             => 'Nayarit',
            'Nuevo León'          => 'Nuevo León',
            'Oaxaca'              => 'Oaxaca',
            'Puebla'              => 'Puebla',
            'Querétaro'           => 'Querétaro',
            'Quintana'            => 'Quintana Roo',
            'San Luis Potosí'     => 'San Luis Potosí',
            'Sinaloa'             => 'Sinaloa',
            'Sonora'              => 'Sonora',
            'Tabasco'             => 'Tabasco',
            'Tamaulipas'          => 'Tamaulipas',
            'Tlaxcala'            => 'Tlaxcala',
            'Veracruz'            => 'Veracruz',
            'Yucatán'             => 'Yucatán',
            'Zacatecas'           => 'Zacatecas'
        ],
];
