version: '3.8'
services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8088:80'

  database: 
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'hadiah'
      MYSQL_ROOT_PASSWORD: 'tiger'
    ports:
      - '3307:3306'
    volumes:
      - ./database/data/mysql:/var/lib/mysql

  frontend:
    build: frontend
    ports:
      - 80:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  backend:
    build: backend
    ports:
      - 81:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      
volumes:
   mysql: {}